# docker-compose.yml  
version: '3.4'  
services:  
  weaviate:  
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.2  
    ports:  
      - "8080:8080"  # HTTP Port
      - "50051:50051" # GRPC Port
    environment:
      QUERY_DEFAULTS_LIMIT: 25  
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'  
      DEFAULT_VECTORIZER_MODULE: 'text2vec-cohere'
      ENABLE_MODULES: 'text2vec-cohere'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      CLUSTER_HOSTNAME: 'node1'
      GRPC_PORT: 50051
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    networks:
      query-network:
        aliases:
          - weaviate

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_HTTP_PORT=8080
      - WEAVIATE_GRPC_PORT=50051
      - PYTHONPATH=${PYTHONPATH}
      - WEAVIATE_GRPC_URL=weaviate:50051
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    networks:
      query-network:
        aliases:
          - api

  chat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python src/chat_interface.py
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_HTTP_PORT=${WEAVIATE_HTTP_PORT}
      - WEAVIATE_GRPC_PORT=${WEAVIATE_GRPC_PORT}
      - PYTHONPATH=${PYTHONPATH}
      - WEAVIATE_GRPC_URL=weaviate:50051
      - API_URL=http://api:8000
    depends_on:
      - weaviate
      - api
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    networks:
      query-network:
        aliases:
          - chat

networks:
  query-network:
    driver: bridge
